# Generated by Django 3.0.8 on 2020-07-10 19:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=50)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulacion.Ciudad')),
            ],
            options={
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{1,2}\\.?\\d{3}\\.?\\d{3}[-]?[0-9kK]{1}$', message='Ingrese un RUT Valido')])),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.BigIntegerField()),
                ('direccion', models.CharField(max_length=75)),
                ('vigente', models.BooleanField(default=True)),
                ('f_postulacion', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('comuna', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='postulacion.Comuna')),
            ],
            options={
                'verbose_name_plural': 'Postulantes',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulacion.Region'),
        ),
    ]
